Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "ubuntu:20.04"
    d.cmd = ["tail", "-f", "/dev/null"]
    d.remains_running = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt install -y bash nano vim procps
  SHELL
end
